package torscmd

import (
	"encoding/json/v2"
	"flag"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"

	"github.com/tori43-hash/tors"
)

// CorePath is the Go module path of the core.
const CorePath = "github.com/tori43-hash/tors"

// cmdBuild compiles a tors binary with exactly the modules a config lists in
// its "build" section — the config the bot builder exports.
func cmdBuild(args []string) error {
	fs := flag.NewFlagSet("build", flag.ContinueOnError)
	path := configFlag(fs)
	out := fs.String("o", "tors", "куда положить бинарь")
	replace := fs.String("replace", "", "путь к локальной копии "+CorePath+" (для разработки)")
	if err := fs.Parse(args); err != nil {
		return err
	}
	body, err := LoadConfigFile(*path)
	if err != nil {
		return err
	}
	// Only the build section matters here: placeholders such as {env.BOT_TOKEN}
	// belong to the machine that runs the bot, not the one that builds it.
	var cfg struct {
		Build *tors.Build `json:"build"`
	}
	if err := json.Unmarshal(body, &cfg); err != nil {
		return fmt.Errorf("конфигурация: %w", err)
	}
	if cfg.Build == nil || len(cfg.Build.Modules) == 0 {
		return fmt.Errorf("в конфигурации нет раздела build со списком модулей")
	}
	output, err := filepath.Abs(*out)
	if err != nil {
		return err
	}
	return Build(*cfg.Build, output, *replace)
}

// Build generates a main package importing the modules and compiles it.
func Build(b tors.Build, output, replace string) error {
	dir, err := os.MkdirTemp("", "tors-build-")
	if err != nil {
		return err
	}
	defer os.RemoveAll(dir)

	var imports strings.Builder
	for _, m := range b.Modules {
		fmt.Fprintf(&imports, "\t_ %q\n", m.Source)
	}
	main := "// Code generated by tors build. DO NOT EDIT.\n\npackage main\n\nimport (\n\ttorscmd \"" + CorePath + "/cmd\"\n\n" + imports.String() + ")\n\nfunc main() { torscmd.Main() }\n"
	gomod := "module tors-custom\n\ngo 1.27\n"
	if replace != "" {
		abs, err := filepath.Abs(replace)
		if err != nil {
			return err
		}
		gomod += fmt.Sprintf("\nrequire %s v0.0.0\n\nreplace %s => %s\n", CorePath, CorePath, abs)
	}
	if err := os.WriteFile(filepath.Join(dir, "main.go"), []byte(main), 0o644); err != nil {
		return err
	}
	if err := os.WriteFile(filepath.Join(dir, "go.mod"), []byte(gomod), 0o644); err != nil {
		return err
	}

	run := func(args ...string) error {
		fmt.Fprintln(os.Stderr, "›", strings.Join(append([]string{"go"}, args...), " "))
		cmd := exec.Command("go", args...)
		cmd.Dir = dir
		cmd.Stdout, cmd.Stderr = os.Stderr, os.Stderr
		cmd.Env = append(os.Environ(), "GOFLAGS=-mod=mod")
		return cmd.Run()
	}
	if replace == "" {
		core := b.Core
		if core == "" {
			core = "latest"
		}
		if err := run("get", CorePath+"@"+core); err != nil {
			return err
		}
	}
	for _, m := range b.Modules {
		if m.Source == CorePath || strings.HasPrefix(m.Source, CorePath+"/") {
			continue
		}
		v := m.Version
		if v == "" {
			v = "latest"
		}
		if err := run("get", m.Source+"@"+v); err != nil {
			return err
		}
	}
	if err := run("mod", "tidy"); err != nil {
		return err
	}
	if err := run("build", "-trimpath", "-o", output, "."); err != nil {
		return err
	}
	fmt.Fprintln(os.Stderr, "Готово:", output)
	return nil
}
